# fly.toml app configuration file generated for phonebook2024 on 2024-02-15T20:18:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook2024'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
